#!/bin/sh
# husky

# Created by Husky v4.3.0 (https://github.com/typicode/husky#readme)
#   At: 10/16/2020, 11:36:56 AM
#   From: undefined (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
